build:
	latexmk -pdf -output-directory=_build gpi_6coursework_pz.tex
	latexmk -pdf -output-directory=_build gpi_6coursework_a.tex
	latexmk -pdf -output-directory=_build gpi_6coursework_b.tex

clean:
	rm -rfv ./*/*.aux
	rm -rfv ./*/*.fdb_latexmk
	rm -rfv ./*/*.fls
	rm -rfv ./*/*.log
	rm -rfv ./*/*.out
	rm -rfv ./*/*.pdf
	rm -rfv ./*/*.synctex.gz
	rm -rfv ./*/*.toc
